#!/usr/bin/env node

//CODE ATTRIBUTION
//01
//Node.js File System Module
//Adapted from: Node.js Foundation. (2025). File system. [online] Node.js Documentation.
//Available at: https://nodejs.org/api/fs.html
//Date Accessed: 10 October 2025

//CODE ATTRIBUTION
//02
//Node.js Process Arguments
//Adapted from: Node.js Foundation. (2025). Process. [online] Node.js Documentation.
//Available at: https://nodejs.org/api/process.html#processargv
//Date Accessed: 10 October 2025

//CODE ATTRIBUTION
//03
//Environment Variable Configuration Best Practices
//Adapted from: Twelve-Factor App. (2025). Config. [online] 12factor.net.
//Available at: https://12factor.net/config
//Date Accessed: 10 October 2025

//CODE ATTRIBUTION
//04
//dotenv - Environment Variable Management
//Adapted from: npm. (2025). dotenv. [online] npm Package Registry.
//Available at: https://www.npmjs.com/package/dotenv
//Date Accessed: 10 October 2025

//CODE ATTRIBUTION
//05
//Node.js Path Module
//Adapted from: Node.js Foundation. (2025). Path. [online] Node.js Documentation.
//Available at: https://nodejs.org/api/path.html
//Date Accessed: 10 October 2025

/**
 * SSL Toggle Script
 * 
 * This script helps you easily switch between HTTP and HTTPS modes
 * for the backend server. It updates the .env file or creates one
 * if it doesn't exist.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envPath = path.join(__dirname, '.env');

// Default environment variables
const defaultEnvVars = {
  PORT: '5000',
  NODE_ENV: 'development',
  MONGODB_URI: 'mongodb://localhost:27017/customer_portal',
  JWT_SECRET: 'your-super-secret-jwt-key-change-this-in-production',
  JWT_EXPIRES_IN: '24h',
  ENABLE_RATE_LIMITING: 'true',
  ENABLE_CSRF_PROTECTION: 'true',
  ENABLE_XSS_PROTECTION: 'true',
  ENABLE_NOSQL_INJECTION_PROTECTION: 'true',
  CORS_ORIGINS: 'http://localhost:3000,http://localhost:5173,https://localhost:5173',
  RATE_LIMIT_MAX: '100',
  RATE_LIMIT_WINDOW_MS: '900000',
  AUTH_RATE_LIMIT_MAX: '5',
  AUTH_RATE_LIMIT_WINDOW_MS: '900000',
  ENABLE_CLOUDFLARE: 'false',
  LOG_LEVEL: 'info',
  ENABLE_REQUEST_LOGGING: 'true',
  SESSION_SECRET: 'your-session-secret-change-this',
  MIN_PASSWORD_LENGTH: '8',
  REQUIRE_PASSWORD_COMPLEXITY: 'true',
  ENABLE_HEALTH_CHECK: 'true',
  HEALTH_CHECK_PATH: '/health'
};

function loadEnvFile() {
  if (!fs.existsSync(envPath)) {
    return {};
  }
  
  const envContent = fs.readFileSync(envPath, 'utf8');
  const envVars = {};
  
  envContent.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
  
  return envVars;
}

function saveEnvFile(envVars) {
  const lines = [];
  
  // Add header comment
  lines.push('# Backend Environment Configuration');
  lines.push('# Generated by toggle-ssl.js script');
  lines.push('');
  
  // Add SSL configuration section
  lines.push('# SSL Configuration');
  lines.push(`FORCE_SSL=${envVars.FORCE_SSL || 'false'}`);
  if (envVars.SSL_KEY_PATH) {
    lines.push(`SSL_KEY_PATH=${envVars.SSL_KEY_PATH}`);
  }
  if (envVars.SSL_CERT_PATH) {
    lines.push(`SSL_CERT_PATH=${envVars.SSL_CERT_PATH}`);
  }
  lines.push('');
  
  // Add other configuration sections
  const sections = [
    { title: 'Server Configuration', keys: ['PORT', 'NODE_ENV'] },
    { title: 'Database Configuration', keys: ['MONGODB_URI'] },
    { title: 'JWT Configuration', keys: ['JWT_SECRET', 'JWT_EXPIRES_IN'] },
    { title: 'Security Configuration', keys: ['ENABLE_RATE_LIMITING', 'ENABLE_CSRF_PROTECTION', 'ENABLE_XSS_PROTECTION', 'ENABLE_NOSQL_INJECTION_PROTECTION'] },
    { title: 'CORS Configuration', keys: ['CORS_ORIGINS'] },
    { title: 'Rate Limiting Configuration', keys: ['RATE_LIMIT_MAX', 'RATE_LIMIT_WINDOW_MS', 'AUTH_RATE_LIMIT_MAX', 'AUTH_RATE_LIMIT_WINDOW_MS'] },
    { title: 'Cloudflare Configuration', keys: ['ENABLE_CLOUDFLARE'] },
    { title: 'Logging Configuration', keys: ['LOG_LEVEL', 'ENABLE_REQUEST_LOGGING'] },
    { title: 'Session Configuration', keys: ['SESSION_SECRET'] },
    { title: 'Password Configuration', keys: ['MIN_PASSWORD_LENGTH', 'REQUIRE_PASSWORD_COMPLEXITY'] },
    { title: 'Health Check Configuration', keys: ['ENABLE_HEALTH_CHECK', 'HEALTH_CHECK_PATH'] }
  ];
  
  sections.forEach(section => {
    lines.push(`# ${section.title}`);
    section.keys.forEach(key => {
      if (envVars[key] !== undefined) {
        lines.push(`${key}=${envVars[key]}`);
      }
    });
    lines.push('');
  });
  
  fs.writeFileSync(envPath, lines.join('\n'));
}

function toggleSSL() {
  const args = process.argv.slice(2);
  const command = args[0];
  
  if (!command || !['enable', 'disable', 'status'].includes(command)) {
    console.log(`
SSL Toggle Script

Usage: node toggle-ssl.js <command>

Commands:
  enable   - Enable HTTPS mode (requires SSL certificates)
  disable  - Disable HTTPS mode (use HTTP only)
  status   - Show current SSL configuration

Examples:
  node toggle-ssl.js enable
  node toggle-ssl.js disable
  node toggle-ssl.js status
`);
    process.exit(1);
  }
  
  const currentEnv = loadEnvFile();
  const envVars = { ...defaultEnvVars, ...currentEnv };
  
  switch (command) {
    case 'enable':
      envVars.FORCE_SSL = 'true';
      saveEnvFile(envVars);
      console.log('✅ SSL/HTTPS mode enabled');
      console.log('📝 Make sure you have SSL certificates in ./cert/ directory');
      console.log('🔄 Restart your server to apply changes');
      break;
      
    case 'disable':
      envVars.FORCE_SSL = 'false';
      saveEnvFile(envVars);
      console.log('✅ SSL/HTTPS mode disabled - using HTTP');
      console.log('🔄 Restart your server to apply changes');
      break;
      
    case 'status':
      console.log('📊 Current SSL Configuration:');
      console.log(`   FORCE_SSL: ${envVars.FORCE_SSL || 'not set (auto-detect)'}`);
      console.log(`   SSL_KEY_PATH: ${envVars.SSL_KEY_PATH || './cert/localhost-key.pem (default)'}`);
      console.log(`   SSL_CERT_PATH: ${envVars.SSL_CERT_PATH || './cert/localhost.pem (default)'}`);
      
      // Check if certificates exist
      const keyPath = envVars.SSL_KEY_PATH || './cert/localhost-key.pem';
      const certPath = envVars.SSL_CERT_PATH || './cert/localhost.pem';
      
      const keyExists = fs.existsSync(path.join(__dirname, keyPath));
      const certExists = fs.existsSync(path.join(__dirname, certPath));
      
      console.log(`   Key file exists: ${keyExists ? '✅' : '❌'}`);
      console.log(`   Cert file exists: ${certExists ? '✅' : '❌'}`);
      
      if (envVars.FORCE_SSL === 'true' && (!keyExists || !certExists)) {
        console.log('⚠️  Warning: SSL enabled but certificates missing!');
        console.log('   Run: node generate-certs.js to create certificates');
      }
      break;
  }
}

toggleSSL();
